title: Curious Cephalopod
description: A graphic designer who has an interest in highlighting the stories behind people's brands has heightended and create logos that embraces the personality
email: enomoto.ariana@gmail.com